bot:
  name: suburb_bot
  token: ${BOT_TOKEN}
yandex-rasp:
  key: ${YANDEX_RASP_API_KEY}
stations:
  first:
    name: Расторгуево
    code: s9600801
  second:
    name: Нагатинская
    code: s9601975
target-TZ: Europe/Moscow